[project]
name = "webctp"
version = "0.1.0"
description = "Homalos webctp"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anyio>=4.12.0",
    "fastapi>=0.123.3",
    "pyyaml>=6.0.3",
    "uvicorn>=0.38.0",
    "websockets>=15.0.1",
]
