[project]
name = "webctp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anyio>=4.12.0",
    "fastapi>=0.123.3",
    "openctp-ctp>=6.7.11.0",
    "pyyaml>=6.0.3",
    "uvicorn>=0.38.0",
    "websockets>=15.0.1",
]
