TdFrontAddress: tcp://182.254.243.31:40001 # 7x24交易前置地址
MdFrontAddress: tcp://182.254.243.31:40011 # 7x24行情前置地址
BrokerID: "9999"
AuthCode: "0000000000000000"
AppID: simnow_client_test
Port: 8080         # the listening port, default 8080
Host: 127.0.0.1      # the bind ip address, default 127.0.0.1
LogLevel: INFO     # NOTSET, DEBUG, INFO, WARN, ERROR, CRITICAL
  
